query boardMeeting($meeting: String) {
  meeting: meetings(where: { id: $meeting }) {
    id
    date
    year
    term
    week
    presentations {
      id
      presenter
      comments
      completeness
      grade
      indicator {
        name
        id
      }
    }
  }
}
