query someQuery {
  boardMeetings {
    id
    date
    year
    term
    week
    indicators {
      name
      boardDateLastNoted
      boardStatusAchieved
      boardStatusProgressNoted
    }
  }
}
