query boardMeeting($meeting: String) {
  meeting: meetings(where: { id: $meeting }) {
    id
    date
    year
    term
    week
    presentations {
      presenter
      comments
      progressStatus
      progressAchieved
      indicator {
        name
      }
    }
  }
}
