query indicatorsByDate($dateStart: DateTime, $dateEnd: DateTime) {
  indicators(
    where: { dateAvailable_gt: $dateStart, dateAvailable_lt: $dateEnd }
  ) {
    name
    id
    type
    value
    target
    rangeLow
    rangeHigh
    focalPoint
    description
    dateAvailable
    stepsToSuccess
    measuring_successes {
      value
    }
    performance_targets {
      value
    }
    strategies_for_improvements {
      value
    }
  }
}
