query indicatorsFiltered($focusArea: String) {
  indicators(
    where: {
      performance_targets: { focus_area: { display_contains: $focusArea } }
    }
  ) {
    name
    id
    type
    value
    target
    rangeLow
    rangeHigh
    focalPoint
    description
    dateAvailable
    stepsToSuccess
    measuring_successes {
      value
    }
    performance_targets {
      value
    }
    strategies_for_improvements {
      value
    }
  }
}
