query indicatorsFiltered($focusArea: String) {
  indicators(
    where: {
      _or: [
        { performance_targets: { focus_area: { display: $focusArea } } }
        { measuring_successes: { focus_area: { display: $focusArea } } }
        { strategies_for_improvements: { focus_area: { display: $focusArea } } }
      ]
    }
  ) {
    name
    id
    type
    value
    target
    rangeLow
    rangeHigh
    updatedAt
    focalPoint
    description
    dateAvailable
    stepsToSuccess
    boardDateLastNoted
    boardStatusAchieved
    boardStatusProgressNoted
    measuring_successes {
      value
    }
    performance_targets {
      value
    }
    strategies_for_improvements {
      value
    }
  }
}
